In [1]:
import numpy as np

In [2]:
mList = [11,22,33,44,55,66,77,88,99]
arr = np.array(mList)

In [3]:
print(f"Datatype {type(arr)}\nValues {arr}\nDepth/Dimension {arr.ndim}\nValue at index 5 is {arr[5]}\nValue at index 0 to 5 {arr[0:5]}")

Datatype <class 'numpy.ndarray'>
Values [11 22 33 44 55 66 77 88 99]
Depth/Dimension 1
Value at index 5 is 66
Value at index 0 to 5 [11 22 33 44 55]


In [5]:
arr

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [6]:
arr*10

array([110, 220, 330, 440, 550, 660, 770, 880, 990])

In [7]:
arr+100

array([111, 122, 133, 144, 155, 166, 177, 188, 199])

In [8]:
arr-9

array([ 2, 13, 24, 35, 46, 57, 68, 79, 90])

In [9]:
arr/100

array([0.11, 0.22, 0.33, 0.44, 0.55, 0.66, 0.77, 0.88, 0.99])

In [10]:
np.round(arr/100,1)

array([0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
print(f"Max {arr.max()}\nMin {arr.min()}\nMean {arr.mean()}\nSum {arr.sum()}")

Max 99
Min 11
Mean 55.0
Sum 495


In [15]:
# Numpy arrays only hold single datatype values
# boolean ----> integer ----> float ----> String (32-bit unicode)
mArr = np.array([11, "oracle",22,33,44,True,False,True,77.89])
mArr

array(['11', 'oracle', '22', '33', '44', 'True', 'False', 'True', '77.89'],
      dtype='<U32')

# Finance data

In [17]:
# input data
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [18]:
revenue = np.array(revenue)
expenses = np.array(expenses)

In [19]:
print(revenue.shape, expenses.shape)
print(revenue.shape == expenses.shape)

(12,) (12,)
True


Caluclate the profit for each month

The data from before belongs to a company's information in the last 12 months

In [20]:
# Calculate the profit
profit = revenue-expenses
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [22]:
# Profit after tax, the taxAmt is of 30%
PAT = profit - (profit*0.3)
PAT

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [27]:
# Profit margin, PAT dividedby revenue, calculated as percentage
# rounded to zero decimals
pMargin = np.round(PAT/revenue*100).astype('int')
pMargin

array([ 12,  18, -30, -22,  -5,  63,  50,  28,  23, -11,   4,  53])

# 2D Arrays/Matrix

In [32]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# To make the array into a matrix/2D array
""""
newShape = (row, col) = row*col = 20
20 because we have 20 elements in our array (created above)
""""

In [33]:
m1 = np.reshape(arr, (5,4))
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
print(m1.ndim, m1.shape)

2 (5, 4)


In [37]:
# Square brackets create 1 array
m2 = np.array([[0,4,8,12],
              [16,1,5,9],
              [13,17,2,6],
              [10,14,18,3],
              [7,11,15,19]])
m2

array([[ 0,  4,  8, 12],
       [16,  1,  5,  9],
       [13, 17,  2,  6],
       [10, 14, 18,  3],
       [ 7, 11, 15, 19]])

In [40]:
# This isn't a matrix multiplication
# each index is being multiplied by the value in the same index
m1+m2

array([[ 0,  5, 10, 15],
       [20,  6, 11, 16],
       [21, 26, 12, 17],
       [22, 27, 32, 18],
       [23, 28, 33, 38]])